### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by sagangwee** [sagangwee/huashing#1]
### Pages
- [x] Home
- [x] Carousel on home page: chinese acupuncture, Hua Wang
- [x] About
- [x] Treatments
- [x] Testimonials
- [x] Finances
- [x] Email contact form on submission
- [ ] Incorporate Google Maps to location on contact page
- [x] Add phone number and location to top of page
- [x] Add relevant information to footer: address + directions, phone number

### Responsive Design
- [x] @media everything
